 
version: "3.3"
services:
  web:
    build: .
    volumes:
      - ./lib:/var/www/zoopix-unleash/lib
    ports:
      - "4242:80"
      - "9229:9229"
    environment:
      PORT: 80
      BASE_URI_PATH: /unleash
      DATABASE_URL: postgres://postgres:unleash@db/postgres
    depends_on:
      - db
    command: nodemon -w lib --inspect=0.0.0.0 server.js
  db:
    expose:
      - "5432"
    image: postgres:10-alpine